spring:
  application:
    name: gatewayserver

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

  data:
    redis:
      port: 6379
      host: localhost
      connect-timeout: 2s
      timeout: 1s

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

services:
  accounts:
    url: "http://localhost:8080"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    urls:
      - name: "accounts-service"
        url: "/aggregate/accounts-service/v3/api-docs"
      - name: "products-service"
        url: "/aggregate/products-service/v3/api-docs"
      - name: "carts-service"
        url: "/aggregate/carts-service/v3/api-docs"
      - name: "orders-service"
        url: "/aggregate/orders-service/v3/api-docs"
      - name: "payment-service"
        url: "/aggregate/payment-service/v3/api-docs"
      - name: "inventory-service"
        url: "/aggregate/inventory-service/v3/api-docs"
      - name: "rates-service"
        url: "/aggregate/rates-service/v3/api-docs"
      - name: "social-service"
        url: "/aggregate/social-service/v3/api-docs"
      - name: "search-service"
        url: "/aggregate/search-service/v3/api-docs"

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
      oralie:
        gatewayserver: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 5000
      failureRateThreshold: 50