spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/oralie/protocol/openid-connect/certs"
          issuer-uri: "http://localhost:7080/realms/oralie"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

services:
  accounts:
    url: "http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "accounts-service"
        url: "/aggregate/accounts-service/v3/api-docs"

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
      oralie:
        gatewayserver: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5000
        failureRateThreshold: 50