spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
      oralie:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5000
        failureRateThreshold: 50