spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
cloud:
  gateway:
    routes:
      - id: accounts_service
        uri: lb://ACCOUNTS
        predicates:
          - Path=/api/accounts/**
        filters:
          - RewritePath=/api/accounts/(?<remaining>.*), /${remaining}
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    httpclient:
      connect-timeout: 1000
      response-timeout: 2s
  #  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
#          jwk-set-uri: "http://localhost:7080/realms/oralie/protocol/openid-connect/certs"
            issuer-uri: "http://localhost:7080/realms/oralie"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

services:
  accounts:
    url: "http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "accounts-service"
        url: "/aggregate/accounts-service/v3/api-docs"

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server application"
    version: "1.0.0"

logging:
  level:
    com:
      oralie:
        gatewayserver: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG

resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 5000
        failureRateThreshold: 50