server:
  port: 8087

spring:
  application:
    name: notification
  mail:
    default-encoding: utf-8
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    test-connection: false
    protocol: smtp

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com:
      oralie:
        notification: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"