spring:
  application:
    name: accounts

  datasource:
    url: jdbc:mysql://localhost:3306/accounts_db
#    ?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  profiles:
    active: "prod"

  config:
    import: "optional:configserver:http://localhost:8071/"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/oralie
#          jwk-set-uri: http://localhost:7080/realms/oralie/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - com.oralie.accounts


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Accounts application"
    version: "1.0.0"

idp:
  url: http://localhost:7080
  client-id: oralie_accounts
  client-secret: CC5JEspbl4tM42MkoWjNr2dvpOf9A6WQ

logging:
  level:
    com:
      oralie:
        accounts: DEBUG

server:
  port: 8080
