package com.oralie.accounts.constant;

public class AccountConstant {
    public static final String ACCOUNT_NOT_FOUND = "Account not found";
    public static final String ACCOUNT_EXISTED = "Account existed";
    public static final String ACCOUNT_CREATED = "Account created";
    public static final String FEIGN_EXCEPTION = "FeignException";
    public static final String ACCOUNT_UPDATED = "Account updated";
    public static final String ACCOUNT_DELETED = "Account deleted";
    public static final String PASSWORD_CHANGED = "Password changed";
    public static final String ACCOUNTS = "Accounts";
    public static final String ACCOUNT = "Account";
    public static final String PASSWORD = "Password";
    public static final String USERNAME = "Username";
    public static final String USER_ID = "User ID";
    public static final String EMAIL = "Email";
    public static final String PHONE = "Phone";
    public static final String FIRST_NAME = "First name";
    public static final String LAST_NAME = "Last name";
    public static final String ADDRESS = "Address";
    public static final String ROLE = "Role";
    public static final String ROLES = "Roles";
    public static final String ROLE_ID = "Role ID";
    public static final String ROLE_NAME = "Role name";
    public static final String ROLE_DESCRIPTION = "Role description";
    public static final String ROLE_NOT_FOUND = "Role not found";
    public static final String ROLE_EXISTED = "Role existed";
    public static final String ROLE_CREATED = "Role created";
    public static final String ROLE_UPDATED = "Role updated";
    public static final String ROLE_DELETED = "Role deleted";
    public static final String ROLE_NAME_REQUIRED = "Role name is required";
    public static final String ROLE_DESCRIPTION_REQUIRED = "Role description is required";
    public static final String ROLE_ID_REQUIRED = "Role ID is required";
    public static final String ROLE_NAME_EXISTED = "Role name existed";
    public static final String ROLE_NOT_FOUND_WITH_ID = "Role not found with ID";
    public static final String ROLE_NOT_FOUND_WITH_NAME = "Role not found with name";
    public static final String ROLE_ID_NOT_FOUND = "Role ID not found";
    public static final String ROLE_NAME_NOT_FOUND = "Role name not found";
    public static final String ROLE_ID_EXISTED = "Role ID existed";
    public static final String ROLE_ID_INVALID = "Role ID invalid";
    public static final String ROLE_NAME_INVALID = "Role name invalid";
    public static final String ROLE_DESCRIPTION_INVALID = "Role description invalid";
    public static final String ROLE_ID_NOT_MATCH = "Role";
    public static final String EMAIL_EXISTED = "Email existed";
    public static final String USERNAME_IS_MISSING = "Username is missing";
    public static final Object UNCATEGORIZED_EXCEPTION = "Uncategorized exception";
}
